tensor_host/main/urls.py
"""Project-level URL Resolution"""
from django.contrib import admin
from django.urls import path, include

from settings.views import SettingForm, index

urlpatterns = [
    path('admin', admin.site.urls),
    path('', index, name='index'),
    path('blocks/', include('blocks.urls')),
    path('capture/', include('capture.urls')),
    path('training/', include('training.urls')),
    path('profiles/', include('profiles.urls')),
    path('sorting/', include('sorting.urls')),
    path('settings/', SettingForm.as_view(), name='settings')
]

tensor_host/training/urls.py
""" URL Resolution for training application """
from django.urls import path

from training.views import Train, TrainingForm

urlpatterns = [
    path('', Train.as_view(), name='training'),
    path('training_form', TrainingForm.as_view(), name='training_form')
]

tensor_host/web_ui/training/urls.py
from django.urls import path

from tensor_host.web_ui.training.views import Train

urlpatterns = [
    path('', Train.as_view()),
]

tensor_host/training/models.py
import uuid

from django.core.exceptions import ValidationError
from django.db import models
from django import forms

from blocks.models import BlockCatalog


class NeuralNets(models.Model):
    """
    id: Primary Key (Unique)
    name: Name of the Neural Network (Unique)
    description: Description of the Neural Network
    blocks: Blocks used to train the Neural Network
    training_status: Boolean field which signifies whether the network has been trained
    """
    # Default parameters
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=256, null=True, blank=True)
    blocks = models.ManyToManyField(BlockCatalog)
    training_status = models.BooleanField(default=False)

    # Distortions
    horizontal_flip = models.BooleanField()
    random_scale = models.IntegerField()
    random_crop = models.IntegerField()
    random_brightness = models.IntegerField()

    # Hyper Parameters
    learning_rate = models.FloatField(default=0.01)
    training_steps = models.IntegerField()

    def __str__(self):
        """ If a string is requested from the model object, return the name of the network """
        return self.name

    class Meta:
        verbose_name_plural = "Neural Networks"


class NeuralNetsForm(forms.ModelForm):
    """ Form to define new neural networks """
    def clean_blocks(self):
        """ Validation Check. Check if at least 2 blocks are selected to train the network. """
        blocks = self.cleaned_data['blocks']
        if blocks.count() < 2:
            raise ValidationError("At least 2 blocks must be chosen to train the network")
        return blocks

    class Meta:
        model = NeuralNets
        verbose_name = "Catalog of all Neural Networks"
        exclude = ['block_count', 'training_status', 'training_time_start', 'training_time_total']

tensor_host/training/views.py
from os import mkdir, getcwd, path
import subprocess
from shutil import copytree

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View

from blocks.views import update_block_count
from training.models import *


class Train(View):
    """ View for /training/ """
    def get(self, request):
        blocks = BlockCatalog.objects.all()
        update_block_count(blocks)
        training_flag = blocks.filter(training_valid=True).count() >= 2
        networks = NeuralNets.objects.all()
        networks = check_networks(networks)
        return render(request, 'training/training.html', {'training_flag': training_flag, "networks": networks})

    @staticmethod
    def post(request):
        """ Delete a neural network """
        network_id = request.POST.get("network_id")
        NeuralNets.objects.get(id=network_id).delete()
        return HttpResponseRedirect('/training')


class TrainingForm(View):
    """ View for /training/training_form/ """
    @staticmethod
    def get(request):
        form = NeuralNetsForm()
        blocks = BlockCatalog.objects.filter(training_valid=True)
        return render(request, 'training/training_form.html', {'form': form, 'blocks': blocks})

    @staticmethod
    def post(request):
        form = NeuralNetsForm(request.POST)
        if form.is_valid():
            network = form.save()
            train_network(network)
            return HttpResponseRedirect('/training/')
        else:
            blocks = BlockCatalog.objects.filter(training_valid=True)
            return render(request, 'training/training_form.html', {'form': form, 'blocks': blocks})


def train_network(network):
    """
    Start a demonised thread to train the network based on the form. Once the training is done, update the network
    entry to reflect that the network is trained and ready to sort parts.
    """
    # Create a new directory for the network nested in the artifacts directory
    network_dir = path.join(getcwd(), "artifacts", "networks", network.name)
    network_dataset_dir = path.join(network_dir, "dataset")

    # Copy image directories of affected blocks to the new dataset directory
    for block in network.blocks.all():
        block_src = path.join(getcwd(), "artifacts", "dataset", str(block.part_number))
        # TODO: Look into using the symlink
        copytree(block_src, path.join(network_dataset_dir, str(block.part_number)))

    mkdir(path.join(network_dir, "trained_model"))
    image_dir = "dataset/"
    bottleneck_dir = "bottleneck/"
    # training_steps = 500
    output_graph = "trained_model/retrained_graph.pb"
    output_labels = "trained_model/retrained_labels.txt"
    exe_path = path.join(getcwd(), "venv/bin/python")
    py_path = path.join(getcwd(), "training/train.py")

    command = [exe_path, py_path, "--image_dir={}".format(image_dir), "--bottleneck_dir={}".format(bottleneck_dir),
               "--how_many_training_steps={}".format(str(network.training_steps)), "--learning_rate={}".format(network.learning_rate),
               "--output_graph={}".format(output_graph), "--output_labels={}".format(output_labels),"--summaries_dir=summaries",
               "--flip_left_right", str(network.horizontal_flip), "--random_brightness", str(network.random_brightness),
               "--random_crop", str(network.random_crop), "--random_scale", str(network.random_scale)]
    print(command)
    with open(path.join(network_dir, "training_log.txt"), "w") as out, \
            open(path.join(network_dir, "error_log.txt"), "w") as err:
        subprocess.Popen(command, cwd=network_dir, stdout=out, stderr=err)


def check_networks(networks):
    """ Check if the *.pb file has been generated for each defined neural networks. """
    for network in networks:
        if path.isfile(path.join(getcwd(), "artifacts/networks", network.name, "trained_model/retrained_graph.pb")):
            network.training_status = True
            network.save()
    return networks

tensor_host/templates/training/training.html
{% extends "base.html" %}

{% block title %}
  Element Sorter - Training
{% endblock %}

{% block additional_css %}
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
{% endblock %}

{% block sidebar %}
  <div class="four wide column" style="margin-left: 2rem">
    <div class="ui menu">
      <div class="ui menu item">
        {% if training_flag %}
        <a style="font-size: large" href="{% url 'training_form' %}">Train New Network <i class="plus icon"></i></a>
        {% else %}
        <a style="font-size: large; color:#aca8a5;">Please Capture More Blocks Before Training</a>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

{% block body %}
  <div class="ten wide stretched column">
    {% if networks %}
      <div class="ui segment">
      <table id="network_table" class="display" style="width:100%;" role="grid">
        <thead>
          <tr role="row">
            <th></th>
            <th class="sorting_asc">Training Status</th>
            <th>Network Name</th>
            <th>Description</th>
            <th>Number of Unique Blocks</th>
          </tr>
        </thead>
        <tbody>
        {% for network in networks %}
          <tr role="row">
              <form method="post" action={{ action }}>
                {% csrf_token %}
                <td><button class="ui tiny red button" name="network_id" value="{{ network.id }}">Delete</button></td>
              </form>
            {% if network.training_status %}
              <td style="text-align: center">
                <i class="ui green large check icon"></i>
              </td>
              {% else %}
              <td style="text-align: center" data-tooltip="Still training network. Please refresh after network has been trained.">
                <i class="ui green large loading sync icon"></i>
              </td>
            {% endif %}
            <td class="sorting_1" style="text-align: center">{{ network.name }}</td>
            <td style="text-align: center">{{ network.description }}</td>
            <td style="text-align: center">{{ network.blocks.all.count }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      </div>
    {% else %}
      <div class="ui warning message">No networks are currently trained. To create a new network, use the link in the left sidebar.</div>
    {% endif %}
  </div>
{% endblock %}

{% block additional_js %}
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script>
    $(document).ready(function() {
        $("#training_item").addClass("active")
    });
    $(".display").DataTable();
  </script>
{% endblock %}

tensor_host/templates/training/training_form.html
{% extends 'base.html' %}

{% block full_content %}
    <div class="ui three wide column"></div>
    <div class="ui ten wide column">
      <div class="ui horizontal divider" style="font-size: large">Train New Neural Network</div>
      <div class="ui segment">
        {% if form.errors %}
          <div class="ui fluid warning message">{{ form.errors }}</div>
        {% endif %}
        <form class="ui form" method="post" action="{{ action }}">
          {% csrf_token %}
          <div class="field">
            <label for=id_name>Name</label>
            <input id="id_name" name="name" type="text" class="ui input" maxlength="64" value="{{ form.name.value|default_if_none:"" }}" required>
          </div>
          <div class="field">
            <label for="id_desc">Description</label>
            <input id="id_desc" name="description" maxlength="256" value="{{ form.description.value|default:"" }}" required>
          </div>
          <div class="field">
            <label for="id_blocks">Blocks</label>
            <select class="ui search dropdown" id="id_blocks" name="blocks" required multiple>
              <option value="">Select Blocks to Include</option>
              {% for block in blocks %}
                <option value="{{ block.part_number }}">{{ block.part_number }}: {{ block.color_wording }} | {{ block.category }} | {{ block.description }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="ui horizontal divider">Distortions</div>
          <div class="ui four fields">
            <div class="ui field">
              <label for="invert">Horizontal Flip</label>
              <select id="invert" name="horizontal_flip" class="ui dropdown" required>
                <option value="1">True</option>
                <option value="0">False</option>
              </select>
            </div>
            <div class="ui field">
              <label for="scaling">Random Scaling</label>
              <input id="scaling" name="random_scale" value="0" required>
            </div>
            <div class="ui field">
              <label for="cropping">Random Cropping</label>
              <input id="cropping" name="random_crop" value="0" required>
            </div>
            <div class="ui field">
              <label for="brightness">Random Brightness</label>
              <input id="brightness" name="random_brightness" value="0" required>
            </div>
          </div>
          <div class="ui horizontal divider">Hyper Parameters</div>
          <div class="ui two fields">
            <div class="ui field">
              <label for="learning_rate">Learning Rate</label>
              <input id="learning_rate" name="learning_rate" value="0.01" required>
            </div>
            <div class="ui field">
              <label for="training_steps">Training Steps</label>
              <input id="training_steps" name="training_steps" value="4000" required>
            </div>
          </div>
          <button class="ui green button" type="submit">Submit <i class="angle double right icon"></i></button>
        </form>
      </div>
    </div>
{% endblock %}

{% block additional_js %}
  <script>
    $(".ui.dropdown").dropdown();
  </script>
{% endblock %}