tensor_host/blocks/urls.py
""" URL Resolution for block application """
from django.urls import path

from blocks.views import BlockProfileEdit
from blocks.views import Blocks, BlockProfile

urlpatterns = [
    path('', Blocks.as_view(), name="block"),
    path('form/', BlockProfile.as_view(), name="block_form"),
    path('form/<int:part_number>', BlockProfileEdit.as_view(), name="block_form_edit")
]

tensor_host/main/urls.py
"""Project-level URL Resolution"""
from django.contrib import admin
from django.urls import path, include

from settings.views import SettingForm, index

urlpatterns = [
    path('admin', admin.site.urls),
    path('', index, name='index'),
    path('blocks/', include('blocks.urls')),
    path('capture/', include('capture.urls')),
    path('training/', include('training.urls')),
    path('profiles/', include('profiles.urls')),
    path('sorting/', include('sorting.urls')),
    path('settings/', SettingForm.as_view(), name='settings')
]

tensor_host/blocks/models.py
""" Model containing all block information """
from django import forms
from django.db import models


class BlockCatalog(models.Model):
    """
    part_number = Catalog number of the part in question
    description = Physical (usually size/shape) description of the part
    category = Part category (i.e. Brick, Plate, etc.)
    photo_count = Number of photos related to this part in the 'artifacts/dataset' directory
    training_valid = Flag which is set once the photo count is high enough to be used to train a network
    """
    part_number = models.IntegerField(primary_key=True)
    description = models.CharField(max_length=128, null=True, blank=True)
    category = models.CharField(max_length=128, blank=True, null=True)
    color_wording = models.CharField(max_length=128)

    photo_count = models.IntegerField(default=0)
    training_valid = models.BooleanField(default=False)

    def __str__(self):
        """ If string is requested from the model object, return the part number """
        return str(self.part_number)

    class Meta:
        verbose_name_plural = "Block Catalog"


class BlockForm(forms.ModelForm):
    """ Django form template based off of the 'Block Catalog' model """
    class Meta:
        model = BlockCatalog
        verbose_name = "Catalog of All Blocks"
        exclude = ['photo_count', 'training_valid']

tensor_host/blocks/views.py
from os import path, listdir, getcwd

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View

from blocks.models import BlockCatalog, BlockForm


class Blocks(View):
    """ View for /blocks/ """
    @staticmethod
    def get(request):
        blocks = BlockCatalog.objects.all()
        update_block_count(blocks)
        return render(request, 'blocks/blocks.html', {'blocks': blocks})


class BlockProfile(View):
    """ View for /blocks/form/ """
    @staticmethod
    def get(request):
        form = BlockForm()
        return render(request, 'blocks/block_form.html', {'form': form})

    @staticmethod
    def post(request):
        form = BlockForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/blocks')
        else:
            return render(request, 'blocks/block_form.html', {'form': form, 'errors': form.errors})


class BlockProfileEdit(View):
    """ View for /blocks/form/ """
    @staticmethod
    def get(request, part_number):
        part = BlockCatalog.objects.get(part_number=part_number)
        form = BlockForm(part)
        return render(request, 'blocks/block_form.html', {'form': form, 'part': part})

    @staticmethod
    def post(request, part_number):
        part = BlockCatalog.objects.get(part_number=part_number)
        form = BlockForm(request.POST, instance=part)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/blocks')
        else:
            return render(request, 'blocks/block_form.html', {'form': form, 'errors': form.errors})


def update_block_count(blocks):
    """
    Update the photo count of the blocks based on what is in the artifacts directory.
    If the number of photos is over the the required threshold,
    :param blocks: Query set of blocks to have their photo count updated
    """
    # TODO: image count should be minimum 200?
    for block in blocks:
        block_artifact_directory = path.join(getcwd(), "artifacts/dataset/", str(block.part_number))
        if path.exists(block_artifact_directory):
            block.photo_count = len([file for file in listdir(block_artifact_directory)])
            if block.photo_count > 1:
                block.training_valid = True
            block.save()

tensor_host/templates/blocks/block_form.html
{% extends "base.html" %}

{% block title %}
  Element Sorter - Blocks
{% endblock %}

{% block full_content %}
  <div class="ui three wide column"></div>
  <div class="ui ten wide column">
    <div class="ui horizontal divider" style="font-size: large">Create/Edit Block Form</div>
    <form class="ui form" method="post" action="{{ action }}">
      {% csrf_token %}
      {% if errors %}
        <div class="error message">{{ errors }}</div>
      {% endif %}
      <div class="ui field">
        <label for="id_part_number">Part number:</label>
        <input type="number" name="part_number" required="" id="id_part_number" placeholder="0123456" value="{{ part.part_number }}">
      </div>
      <div class="ui field">
        <label for="id_description">Description:</label>
        <input type="text" name="description" maxlength="128" id="id_description" placeholder="Describe the piece so it is identifiable" value="{{ part.description }}">
      </div>
      <div class="ui field">
        <label for="id_category">Category:</label>
        <input type="text" name="category" maxlength="128" id="id_category" placeholder="Bricks with slope" value="{{ part.category }}">
      </div>
      <div class="ui field">
        <label for="id_color_wording">Color Description:</label>
        <select name="color_wording" required="" id="id_color_wording" class="ui search dropdown">
          <option value="{{ part.color_wording }}">{{ part.color_wording|default_if_none:"Select Color" }}</option>
          <option value="White">White</option>
          <option value="Grey">Grey</option>
          <option value="Brick Yellow">Yellow, Brick</option>
          <option value="Nougat">Nougat</option>
          <option value="Bright Red">Red, Bright</option>
          <option value="Bright Blue">Blue, Bright</option>
          <option value="Bright Yellow">Yellow, Bright</option>
          <option value="Black">Black</option>
          <option value="Dark Green">Green, Dark</option>
          <option value="Medium Green">Green, Medium</option>
          <option value="Bright Green">Green, Bright</option>
          <option value="Dark Orange">Orange, Dark</option>
          <option value="Transparent">Transparent</option>
          <option value="Transparent Red">Red, Transparent</option>
          <option value="Transparent Light Blue">Blue, Transparent, Light</option>
          <option value="Transparent Blue">Blue, Transparent</option>
          <option value="Transparent Yellow">Yellow, Transparent</option>
          <option value="Light Blue">Blue, Light</option>
          <option value="Transparent Florescent Green">Green, Transparent, Florescent</option>
          <option value="Medium Blue">Blue, Medium</option>
          <option value="Bright Orange">Orange, Bright</option>
          <option value="Bright Blue-Green">Blue-Green, Bright</option>
          <option value="Transparent Brown">Brown, Transparent</option>
          <option value="Transparent Mid Red Violet">Red, Violet, Transparent, Mid</option>
          <option value="Bright Yellow-Green">Yellow-Green, Bright</option>
          <option value="Bright Red Violet">Red, Violet, Bright</option>
          <option value="Transparent Blue Violet">Violet, Blue, Transparent</option>
          <option value="Sand Blue">Blue, Sand</option>
          <option value="Sand Yellow">Yellow, Sand</option>
          <option value="Earth Blue">Blue, Earth</option>
          <option value="Earth Green">Green, Earth</option>
          <option value="Sand Green">Green, Sand</option>
          <option value="New Dark Red">Red, Dark, New</option>
          <option value="Transparent Bright Orange">Orange, Transparent, Bright</option>
          <option value="Florescent Yellow Orange">Yellow-Orange, Florescent</option>
          <option value="Red Brown">Red Brown</option>
          <option value="Medium Stone Grey">Grey, Medium, Stone</option>
          <option value="Dark Stone Grey">Grey, Dark, Stone</option>
          <option value="Light Royal Blue">Blue, Royal, Light</option>
          <option value="Bright Purple">Purple, Bright</option>
          <option value="Light Purple">Purple, Light</option>
          <option value="Cool Yellow">Yellow, Cool</option>
          <option value="Transparent Bright Red">Red, Transparent, Bright</option>
          <option value="Medium Lilac">Medium Lilac</option>
          <option value="Light Nougat">Nougat, Light</option>
          <option value="White Gold">White Gold</option>
          <option value="Dark Brown">Brown, Dark</option>
          <option value="Medium Nougat">Nougat, Medium</option>
          <option value="Transparent Bright Green">Green, Transparent, Bright</option>
          <option value="Silver Metal">Silver Metal</option>
          <option value="Titanium Metal">Titanium Metal</option>
          <option value="Dark Azure">Azure, Dark</option>
          <option value="Medium Azure">Azure, Medium </option>
          <option value="Aqua">Aqua</option>
          <option value="Medium Lavendar">Lavender, Medium /option>
          <option value="Lavender">Lavender</option>
          <option value="Spring Yellow-Green">Yellow-Green, Spring</option>
          <option value="Olive Green">Green, Olive</option>
        </select>
      </div>
      <button class="ui green button" type="submit">Submit <i class="angle double right icon"></i></button>
    </form>
  </div>
{% endblock %}

{% block additional_js %}
  <script>
  $('select.dropdown').dropdown();
  $(document).ready(function () {
      $("#blocks_item").addClass("active")
  })
  </script>
{% endblock %}

tensor_host/templates/blocks/blocks.html
{% extends "base.html" %}

{% block title %}
  Element Sorter - Blocks
{% endblock %}

{% block additional_css %}
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
{% endblock %}

{% block sidebar %}
  <div class="four wide column" style="margin-left: 2rem">
  <div class="ui menu">
    <div class="ui menu item">
      <a style="font-size:large" href="{% url 'block_form' %}">Create New Block <i class="plus icon"></i> </a>
    </div>
  </div>
  </div>
{% endblock %}

{% block body %}
  <div class="ten wide stretched column">
    {% if blocks %}
      <div class="ui segment">
      <table id="block_table" class="display" style="width:100%;" role="grid">
      <thead>
      <tr role="row">
        <th class="sorting_asc" tabindex="0" rowspan="1" colspan="1" style="width: 152px">Part Number</th>
        <th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 236px;">Color</th>
        <th class="sorting_asc" tabindex="0" rowspan="1" colspan="1" style="width: 113px">Photo Count</th>
        <th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 200px">Category</th>
        <th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 200px">Description</th>
      </tr>
      </thead>
      <tbody>
      {% for block in blocks %}
        <tr role="row">
          <td class="sorting_1" tabindex="0"><a href="{% url 'block_form_edit' block.part_number %}">{{ block.part_number }}</a></td>
          <td>{{ block.color_wording }}</td>
          <td>{{ block.photo_count }}</td>
          <td>{{ block.category }}</td>
          <td>{{ block.description }}</td>
        </tr>
      {% endfor %}
    {% else %}
      <div class="ui warning message">No blocks are currently in the database. To create new blocks use the link in the
        left sidebar.
      </div>
    {% endif %}
    </tbody>
    </table>
  </div>
  </div>
{% endblock %}

{% block additional_js %}
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script>
    $(document).ready(function () {
        $('#block_table').DataTable();
        $("#blocks_item").addClass("active")
    });
  </script>

{% endblock %}