tensor_host/main/urls.py
"""Project-level URL Resolution"""
from django.contrib import admin
from django.urls import path, include

from settings.views import SettingForm, index

urlpatterns = [
    path('admin', admin.site.urls),
    path('', index, name='index'),
    path('blocks/', include('blocks.urls')),
    path('capture/', include('capture.urls')),
    path('training/', include('training.urls')),
    path('profiles/', include('profiles.urls')),
    path('sorting/', include('sorting.urls')),
    path('settings/', SettingForm.as_view(), name='settings')
]

tensor_host/settings/models.py
""" Model containing all settings information """
from django.db import models
from django import forms


class ElementSettings(models.Model):
    """ Model to store the setting for the Element system. """
    rpi_id_addr1 = models.GenericIPAddressField()
    rpi_id_addr2 = models.GenericIPAddressField()
    tolerance = models.FloatField()


class ElementSettingForm(forms.ModelForm):
    """ Form to construct the new setting """
    class Meta:
        model = ElementSettings
        verbose_name = "Form for Project-wide Setting"
        exclude = []

tensor_host/settings/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View

from settings.models import ElementSettingForm, ElementSettings


def index(request):
    """ View for / (landing page) """
    return render(request, 'settings/index.html')


class SettingForm(View):
    """ View for /settings/ """
    @staticmethod
    def get(request):
        setting_instance = ElementSettings.objects.first()
        form = ElementSettingForm()
        if setting_instance:
            form = ElementSettingForm(instance=setting_instance)
        return render(request, 'settings/setting_form.html', {'form': form, 'setting_instance': setting_instance})

    @staticmethod
    def post(request):
        setting_instance = ElementSettings.objects.first()
        form = ElementSettingForm(request.POST, instance=setting_instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/")
        else:
            return render(request, 'settings/setting_form.html', {'form': form, 'setting_instance': setting_instance})

tensor_host/templates/settings/index.html
{% extends 'base.html' %}

{% block full_content %}
  <div class="ui three wide column"></div>
  <div class="ui ten wide column segment">
    <div class="ui horizontal divider" style="font-size: large">Instruction Guide</div>
    <div class="ui info message">
      <pre style="font-size: medium">
          This website is used to collect, train, and enact sorting by the Element Sorter. The following
        steps are used in creating a new neural net sorting profile:

        1. In the "Blocks" tab, create any number of elements to represent your Lego Collection.

        2. In the "Capture" tab, select a block that you would like to train. Fill the machine's
          hopper with as many of that block as you would like. Click the run button which will
          take image captures of the block. Click stop after you are done to end the capture loop.

        3. Once you have captured multiple blocks, it is time to train your network. In the
          "Training" tab, use the form to submit a new network mapping. The software will then
          begin the training process (it takes some time). Once the training is completed, you will
          be able to use the network to build profiles.

        4. Profiles, accessed through the "Profiles" tab, are used to tell the machine what to do
          with the part once it is identified. Using the profile's form, select the network you would like
          to profile. For each bin, select the part(s) that you would like to sort into it respectively.
          Note that a single network can have multiple profiles.

        5. In the "Sorting" tab, select the profile you would like to use and click the run button.
          The machine will sort the Lego elements until you click the stop button.
      </pre>
    </div>
  </div>
{% endblock %}

tensor_host/templates/settings/setting_form.html
{% extends 'base.html' %}

{% block title %}
  Element Sorter - Settings
{% endblock %}

{% block full_content %}
    <div class="ui three wide column"></div>
    <div class="ui ten wide column">
    <div class="ui horizontal divider" style="font-size: large">Settings Form</div>
      {% if form.errors %}
        <div class="ui error message">{{ form.errors }}</div>
      {% endif %}
      <form class="ui form" method="post" action="{{ action }}">
        {% csrf_token %}
        <div class="ui field">
          <label for="rpi_addr">Raspberry Pi IP Address</label>
          <input id="rpi_addr" name="rpi_id_addr" required type="text" placeholder="http://192.168.0.12" value="{{ setting_instance.rpi_id_addr }}">
        </div>
        <div class="ui warning message">The tolerance is the percentage match that a captured image is recognised by the neural network. Increasing the percentage will result in fewer bad sorts; however, will result in multiple parts not being sorted.</div>
        <div class="ui field">
          <label for="id_tolerance">Tolerance Percentage</label>
          <select id="id_tolerance" name="tolerance" required>
            <option value="">Select a Tolerance</option>
            <option value=".7">70%</option>
            <option value=".75">75%</option>
            <option value=".8">80%</option>
            <option value=".85">85%</option>
            <option value=".9">90%</option>
            <option value=".95">95%</option>
          </select>
        </div>
        <button class="ui green button" type="submit">Submit <i class="angle double right icon"></i></button>
      </form>
    </div>
{% endblock %}

{% block additional_js %}
  <script>
    $(document).ready(function() {
        $("#setting_item").addClass("active")
    })
  </script>
{% endblock %}